services:
  sqlserver:
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"

  be-zsm:
    build:
      context: .
      dockerfile: Dockerfile

    image: be-zsm-local

    environment:
      ASPNETCORE_ENVIRONMENT: Development